/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Bank, BuyerCompany, TransactionOrder } from './types';

export const BANKS: Bank[] = [
  { id: 'bank-1', name: 'Aktiv Bank' },
  { id: 'bank-2', name: 'IBT Bank' },
  { id: 'bank-3', name: 'Dushanbe City Bank' },
];

export const BUYER_COMPANIES: BuyerCompany[] = [
  { id: 'comp-1', name: 'LLC KORVONSAROI CHIN', bankId: 'bank-1' },
  { id: 'comp-2', name: 'LLC RUSHDI HISOR', bankId: 'bank-2' },
  { id: 'comp-3', name: 'Hasan Iskandar', bankId: 'bank-1' },
  { id: 'comp-4', name: 'Caravanserai China', bankId: 'bank-1' },
  { id: 'comp-5', name: 'Rushdi Duston', bankId: 'bank-2' },
];

export const BENEFICIARIES = [
  'JABS INTERNATIONAL PVT. LTD',
  'NGO CHEW HONG EDIBLE OIL PTE LTD',
  'ISONIYA GROUP LIMITED',
  'LI XIAN SAI NI TEXTILE CO., LTD',
  'SICHUAN SHINE MAY IMP. AND EXP. TRADING CO., LTD',
];

export const SAMPLE_ORDERS: TransactionOrder[] = [
  {
    id: 'ord-1',
    orderNo: 'ORD-2024-001',
    date: '2024-04-24 09:15',
    bankId: 'bank-1',
    buyerCompanyId: 'comp-1',
    beneficiaryName: 'JABS INTERNATIONAL PVT. LTD',
    currency: 'USD',
    amount: 125000.00,
    contractNo: 'CONT/2024/0045',
    accountNo: '88234455667788',
    swiftBic: 'JABINBB77XXX',
    status: 'Completed',
    risk: 'Low',
    matchScore: 100,
    sourceType: 'WhatsApp',
    beneficiaryBank: 'HDFC BANK LTD',
    hasContract: true,
    hasPayment: true,
    hasSwift: true,
  },
  {
    id: 'ord-2',
    orderNo: 'ORD-2024-002',
    date: '2024-04-24 10:30',
    bankId: 'bank-2',
    buyerCompanyId: 'comp-2',
    beneficiaryName: 'NGO CHEW HONG EDIBLE OIL PTE LTD',
    currency: 'USD',
    amount: 85200.50,
    contractNo: 'CONT/2024/0089',
    accountNo: '11223344556677',
    swiftBic: 'NGCHSG88XXX',
    status: 'SWIFT',
    risk: 'Medium',
    matchScore: 95,
    sourceType: 'PDF',
    beneficiaryBank: 'DBS BANK SINGAPORE',
    hasContract: true,
    hasPayment: true,
    hasSwift: true,
  },
  {
    id: 'ord-3',
    orderNo: 'ORD-2024-003',
    date: '2024-04-24 11:45',
    bankId: 'bank-1',
    buyerCompanyId: 'comp-3',
    beneficiaryName: 'ISONIYA GROUP LIMITED',
    currency: 'CNY',
    amount: 1450000.00,
    contractNo: 'CN-1200334',
    accountNo: '33445566778899',
    swiftBic: 'ISONHKHHXXX',
    status: 'Contract Created',
    risk: 'High',
    matchScore: 65,
    sourceType: 'WhatsApp',
    beneficiaryBank: 'ICBC HONG KONG',
    hasContract: true,
    hasPayment: false,
    hasSwift: false,
  },
  {
    id: 'ord-4',
    orderNo: 'ORD-2024-004',
    date: '2024-04-24 13:20',
    bankId: 'bank-3',
    buyerCompanyId: 'comp-4',
    beneficiaryName: 'LI XIAN SAI NI TEXTILE CO., LTD',
    currency: 'CNY',
    amount: 678000.00,
    accountNo: '66778899001122',
    swiftBic: 'LXSNCNBJXXX',
    status: 'WhatsApp Order',
    risk: 'Critical',
    matchScore: 20,
    sourceType: 'Image',
    beneficiaryBank: 'BANK OF CHINA',
    hasContract: false,
    hasPayment: false,
    hasSwift: false,
  },
  {
    id: 'ord-5',
    orderNo: 'ORD-2024-005',
    date: '2024-04-24 14:05',
    bankId: 'bank-1',
    buyerCompanyId: 'comp-1',
    beneficiaryName: 'SICHUAN SHINE MAY IMP. AND EXP. TRADING CO., LTD',
    currency: 'USD',
    amount: 45000.00,
    contractNo: 'CONT-2024-99',
    accountNo: '99001122334455',
    swiftBic: 'SCSMCNCHXXX',
    status: 'Bank Payment Instruction',
    risk: 'Low',
    matchScore: 88,
    sourceType: 'Word',
    beneficiaryBank: 'CHENGDU BANK',
    hasContract: true,
    hasPayment: true,
    hasSwift: false,
  }
];
